class Names
{
    static String[] nameList = {"AMELIA", "OLIVIA", "EMILY", "AVA", "ISLA", "JESSICA", "POPPY", "ISABELLA", "SOPHIE", "MIA", "RUBY", "LILY", "GRACE", "EVIE", "SOPHIA", "ELLA", "SCARLETT", "CHLOE", "ISABELLE", "FREYA" , "CHARLOTTE", "SIENNA", "DAISY", "PHOEBE", "MILLIE" , "EVA" , "ALICE" , "LUCY" , "FLORENCE", "SOFIA",
            "OLIVER" , "JACK" , "HARRY" , "JACOB" , "CHARLIE" , "THOMAS" , "OSCAR" , "WILLIAM" , "JAMES" , "GEORGE" , "ALFIE" , "JOSHUA" , "NOAH" , "ETHAN" , "MUHAMMAD" , "ARCHIE" , "LEO" , "HENRY" , "JOSEPH" , "SAMUEL" , "RILEY" , "DANIEL" , "MOHAMMED" , "ALEXANDER" , "MAX" , "LUCAS" , "MASON" , "LOGAN" , "ISAAC", "BENJAMIN"};


}
